ALTER TABLE registrations ADD COLUMN IF NOT EXISTS gender TEXT;
ALTER TABLE registrations ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS gender TEXT;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS phone TEXT;
